export const FETCH_WISHLIST_BEGIN = "FETCH_WISHLIST_BEGIN";
export const FETCH_WISHLIST_SUCCESS = "FETCH_WISHLIST_SUCCESS";
export const FETCH_WISHLIST_ERROR = "FETCH_WISHLIST_ERROR";

export const POST_WISHLIST_SUCCESS = "POST_WISHLIST_SUCCESS";
export const POST_WISHLIST_ERROR = "POST_WISHLIST_ERROR";
