export const GIG_FETCH_BEGIN = "GIG_FETCH_BEGIN"
export const GIG_FETCH_SUCCESS = "GIG_FETCH_SUCCESS"
export const GIG_FETCH_ERROR = "GIG_FETCH_ERROR"

export const GIGSTATUS_FETCH_BEGIN = "GIGSTATUS_FETCH_BEGIN";
export const GIGSTATUS_FETCH_SUCCESS = "GIGSTATUS_FETCH_SUCCESS";
export const GIGSTATUS_FETCH_ERROR = "GIGSTATUS_FETCH_ERROR";

export const SINGLEGIG_FETCH_BEGIN = "SINGLEGIG_FETCH_BEGIN";
export const SINGLEGIG_FETCH_SUCCESS = "SINGLEGIG_FETCH_SUCCESS";
export const SINGLEGIG_FETCH_ERROR = "SINGLEGIG_FETCH_ERROR";

export const GIG_DELETE_BEGIN = "GIG_DELETE_BEGIN";
export const GIG_DELETE_SUCCESS = "GIG_DELETE_SUCCESS";
export const GIG_DELETE_ERROR = "GIG_DELETE_ERROR";


