export const POST_SEARCH_BEGIN = "POST_SEARCH_BEGIN";
export const POST_SEARCH_SUCCESS = "POST_SEARCH_SUCCESS";
export const POST_SEARCH_ERROR = "POST_SEARCH_ERROR";

export const FETCH_SEARCH_BEGIN = "FETCH_SEARCH_BEGIN";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_ERROR = "FETCH_SEARCH_ERROR";

export const SET_FILTERDATA_SUCCESS = "SET_FILTERDATA_SUCCESS";
