export const PERSONAL_INFO_LOADING = "PERSONAL_INFO_LOADING";
export const PERSONAL_INFO_SUCCESS = "PERSONAL_INFO_SUCCESS";
export const PERSONAL_INFO_ERROR = "PERSONAL_INFO_ERROR";

export const PROFILE_INFO_LOADING = "PROFILE_INFO_LOADING";
export const PROFILE_INFO_SUCCESS = "PROFILE_INFO_SUCCESS";
export const PROFILE_INFO_ERROR = "PROFILE_INFO_ERROR";

export const COUNTRY_CODE_LOADING = "COUNTRY_CODE_LOADING";
export const COUNTRY_CODE_SUCCESS = "COUNTRY_CODE_SUCCESS";
export const COUNTRY_CODE_ERROR = "COUNTRY_CODE_ERROR";

export const PHONE_NUMBER_VERIFICATION_LOADING =
	"PHONE_NUMBER_VERIFICATION_LOADING";
export const PHONE_NUMBER_VERIFICATION_SUCCESS =
	"PHONE_NUMBER_VERIFICATION_SUCCESS";
export const PHONE_NUMBER_VERIFICATION_ERROR =
	"PHONE_NUMBER_VERIFICATION_ERROR";

export const PROFILE_COMPLETE_LOADING = "PROFILE_COMPLETE_LOADING";
export const PROFILE_COMPLETE_SUCCESS = "PROFILE_COMPLETE_SUCCESS";
export const PROFILE_COMPLETE_ERROR = "PROFILE_COMPLETE_ERROR";

export const PROFILE_FETCH_LOADING = "PROFILE_FETCH_LOADING";
export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";
export const PROFILE_FETCH_ERROR = "PROFILE_FETCH_ERROR";

export const PROFILEGIG_FETCH_LOADING = "PROFILEGIG_FETCH_LOADING";
export const PROFILEGIG_FETCH_SUCCESS = "PROFILEGIG_FETCH_SUCCESS";
export const PROFILEGIG_FETCH_ERROR = "PROFILEGIG_FETCH_ERROR";

export const FORM_ACTION_SAVE = "FORM_ACTION_SAVE";

export const POST_ACTION_BEGIN = "POST_ACTION_BEGIN";
export const POST_ACTION_COMPLETE = "POST_ACTION_COMPLETE";

export const EDIT_ACTION_BEGIN = "EDIT_ACTION_BEGIN";
export const EDIT_ACTION_COMPLETE = "EDIT_ACTION_COMPLETE";
