export const FETCH_RESOLUTION_BEGIN = "FETCH_RESOLUTION_BEGIN";
export const FETCH_RESOLUTION_SUCCESS = "FETCH_RESOLUTION_SUCCESS";
export const FETCH_RESOLUTION_ERROR = "FETCH_RESOLUTION_ERROR";

export const HANDLE_POST_BEGIN = "HANDLE_POST_BEGIN";
export const HANDLE_POST_COMPLETE = "HANDLE_POST_COMPLETE";

export const CANCEL_ORDER_BUYER_BEGIN = "CANCEL_ORDER_BUYER_BEGIN";
export const CANCEL_ORDER_BUYER_COMPLETE = "CANCEL_ORDER_BUYER_COMPLETE";
