export const GIG_DETAILS_LOADING = "GIG_DETAILS_LOADING"
export const GIG_DETAILS_SUCCESS = "GIG_DETAILS_SUCCESS"
export const GIG_DETAILS_ERROR = "GIG_DETAILS_ERROR"

export const GIG_FEEDBACK_LOADING = "GIG_FEEDBACK_LOADING"
export const GIG_FEEDBACK_SUCCESS = "GIG_FEEDBACK_SUCCESS"
export const GIG_FEEDBACK_ERROR = "GIG_FEEDBACK_ERROR"



export const UPDATE_FILTER_DATA = "UPDATE_FILTER_DATA"

