export const FETCH_SELLERDASHBOARD_BEGIN = "FETCH_SELLERDASHBOARD_BEGIN";
export const FETCH_SELLERDASHBOARD_SUCCESS= "FETCH_SELLERDASHBOARD_SUCCESS";
export const FETCH_SELLERDASHBOARD_ERROR = "FETCH_SELLERDASHBOARD_ERROR";