export const FETCH_CHATGIG_BEGIN = "FETCH_CHATGIG_BEGIN";
export const FETCH_CHATGIG_SUCCESS = "FETCH_CHATGIG_SUCCESS";
export const FETCH_CHATGIG_ERROR = "FETCH_CHATGIG_ERROR";

export const FETCH_OFFEROPTION_BEGIN = "FETCH_OFFEROPTION_BEGIN";
export const FETCH_OFFEROPTION_SUCCESS = "FETCH_OFFEROPTION_SUCCESS";
export const FETCH_OFFEROPTION_ERROR = "FETCH_OFFEROPTION_ERROR";