export const POST_COMPLETE = "POST_COMPLETE";
export const POST_BEGIN = "POST_BEGIN";

export const FETCH_CUSTOMREQUEST_BEGIN = "GET_CUSTOMREQUEST_BEGIN";
export const FETCH_CUSTOMREQUEST_SUCCESS = "GET_CUSTOMREQUEST_SUCCESS";
export const FETCH_CUSTOMREQUEST_ERROR = "GET_CUSTOMREQUEST_ERROR";

export const FETCH_OFFERS_BEGIN = "FETCH_OFFERS_BEGIN";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_ERROR = "FETCH_OFFERS_ERROR";

