export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

export const CATEGORY_SLUG_LOADING = "CATEGORY_SLUG_LOADING";
export const CATEGORY_SLUG_SUCCESS = "CATEGORY_SLUG_SUCCESS";
export const CATEGORY_SLUG_ERROR = "CATEGORY_SLUG_ERROR";