export const FETCH_STARTCHAT_BEGIN = "FETCH_STARTCHAT_BEGIN";
export const FETCH_STARTCHAT_SUCCESS = "FETCH_STARTCHAT_SUCCESS";
export const FETCH_STARTCHAT_ERROR = "FETCH_STARTCHAT_ERROR";

export const FETCH_CHATLIST_BEGIN = "FETCH_CHATLIST_BEGIN";
export const FETCH_CHATLIST_SUCCESS = "FETCH_CHATLIST_SUCCESS";
export const FETCH_CHATLIST_ERROR = "FETCH_CHATLIST_ERROR";

export const FETCH_USERMESSAGE_BEGIN = "FETCH_USERMESSAGE_BEGIN";
export const FETCH_USERMESSAGE_SUCCESS = "FETCH_USERMESSAGE_SUCCESS";
export const FETCH_USERMESSAGE_ERROR = "FETCH_USERMESSAGE_ERROR";

export const ADD_USERMESSAGE = "ADD_USERMESSAGE";
export const ADD_CHATLIST = "ADD_CHATLIST";
export const APPEND_USERMESSAGE = "APPEND_USERMESSAGE";
export const CHANGE_SEEN_USERMESSAGE = "CHANGE_SEEN_USERMESSAGE";