export const FETCH_SITESETTING_BEGIN = "FETCH_SITESETTING_BEGIN"
export const FETCH_SITESETTING_SUCCESS = "FETCH_SITESETTING_SUCCESS";
export const FETCH_SITESETTING_ERROR = "FETCH_SITESETTING_ERROR";