export const FETCH_FREELANCER_BEGIN = "FETCH_FREELANCER_BEGIN";
export const FETCH_FREELANCER_SUCCESS = "FETCH_FREELANCER_SUCCESS";
export const FETCH_FREELANCER_ERROR = "FETCH_FREELANCER_ERROR";

export const FETCH_FREELANCER_REVIEW_BEGIN = "FETCH_FREELANCER_REVIEW_BEGIN";
export const FETCH_FREELANCER_REVIEW_SUCCESS =
	"FETCH_FREELANCER_REVIEW_SUCCESS";
export const FETCH_FREELANCER_REVIEW_ERROR = "FETCH_FREELANCER_REVIEW_ERROR";
