export const FETCH_BUYERREQUEST_BEGIN = "FETCH_BUYERREQUEST_BEGIN";
export const FETCH_BUYERREQUEST_SUCCESS = "FETCH_BUYERREQUEST_SUCCESS";
export const FETCH_BUYERREQUEST_ERROR = "FETCH_BUYERREQUEST_ERROR";

export const FETCH_SENTOFFER_BEGIN = "FETCH_SENTOFFER_BEGIN";
export const FETCH_SENTOFFER_SUCCESS = "FETCH_SENTOFFER_SUCCESS";
export const FETCH_SENTOFFER_ERROR = "FETCH_SENTOFFER_ERROR";

export const POST_COMPLETE = "POST_COMPLETE";
export const POST_BEGIN = "POST_BEGIN";