export const ORDER_FETCH_BEGIN = "ORDER_FETCH_BEGIN"
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS"
export const ORDER_FETCH_ERROR = "ORDER_FETCH_ERROR"
export const ORDERSTATUS_FETCH_BEGIN = "ORDERSTATUS_FETCH_BEGIN";
export const ORDERSTATUS_FETCH_SUCCESS = "ORDERSTATUS_FETCH_SUCCESS";
export const ORDERSTATUS_FETCH_ERROR = "ORDERSTATUS_FETCH_ERROR";
export const SINGLEORDER_FETCH_BEGIN = "SINGLEORDER_FETCH_BEGIN";
export const SINGLEORDER_FETCH_SUCCESS = "SINGLEORDER_FETCH_SUCCESS";
export const SINGLEORDER_FETCH_ERROR = "SINGLEORDER_FETCH_ERROR";
export const MODIFYORDER_FETCH_BEGIN = "MODIFYORDER_FETCH_BEGIN";
export const MODIFYORDER_FETCH_SUCCESS = "MODIFYORDER_FETCH_SUCCESS";
export const MODIFYORDER_FETCH_ERROR = "MODIFYORDER_FETCH_ERROR";

export const HANDLE_POST_BEGIN = "HANDLE_POST_BEGIN";
export const HANDLE_POST_COMPLETE = "HANDLE_POST_COMPLETE";



