export const CATEGORYPACKAGEMETA_FETCH_BEGIN = "CATEGORYPACKAGEMETA_FETCH_BEGIN"
export const CATEGORYPACKAGEMETA_FETCH_SUCCESS = "CATEGORYPACKAGEMETA_FETCH_SUCCESS"
export const CATEGORYPACKAGEMETA_FETCH_ERROR = "CATEGORYPACKAGEMETA_FETCH_ERROR"

export const PACKAGE_FETCH_BEGIN = "PACKAGE_FETCH_BEGIN"
export const PACKAGE_FETCH_SUCCESS = "PACKAGE_FETCH_SUCCESS";
export const PACKAGE_FETCH_ERROR = "PACKAGE_FETCH_ERROR";

export const PRICELIMIT_FETCH_BEGIN = "PRICELIMIT_FETCH_BEGIN"
export const PRICELIMIT_FETCH_SUCCESS = "PRICELIMIT_FETCH_SUCCESS";
export const PRICELIMIT_FETCH_ERROR = "PRICELIMIT_FETCH_ERROR";
