export const FETCH_FAQ_PARENT_BEGIN = "FETCH_FAQ_PARENT_BEGIN";
export const FETCH_FAQ_PARENT_SUCCESS = "FETCH_FAQ_PARENT_SUCCESS";
export const FETCH_FAQ_PARENT_ERROR = "FETCH_FAQ_PARENT_ERROR";

export const FETCH_FAQ_CHILD_BEGIN = "FETCH_FAQ_CHILD_BEGIN";
export const FETCH_FAQ_CHILD_SUCCESS = "FETCH_FAQ_CHILD_SUCCESS";
export const FETCH_FAQ_CHILD_ERROR = "FETCH_FAQ_CHILD_ERROR";

export const FETCH_FAQ_SINGLE_BEGIN = "FETCH_FAQ_SINGLE_BEGIN";
export const FETCH_FAQ_SINGLE_SUCCESS = "FETCH_FAQ_SINGLE_SUCCESS";
export const FETCH_FAQ_SINGLE_ERROR = "FETCH_FAQ_SINGLE_ERROR";
