export const FETCH_HELP_BEGIN = "FETCH_HELP_BEGIN";
export const FETCH_HELP_SUCCESS = "FETCH_HELP_SUCCESS";
export const FETCH_HELP_ERROR = "FETCH_HELP_ERROR";

export const POST_HELP_SUCCESS = "POST_HELP_SUCCESS";
export const POST_HELP_ERROR = "POST_HELP_ERROR";
