export const NOTIFICATION_FETCH_BEGIN = "NOTIFICATION_FETCH_BEGIN";
export const NOTIFICATION_FETCH_SUCCESS = "NOTIFICATION_FETCH_SUCCESS";
export const NOTIFICATION_FETCH_ERROR = "NOTIFICATION_FETCH_ERROR";



export const NOTIFICATION_PUSHER_ADD = "NOTIFICATION_PUSHER_ADD";
export const MESSAGE_PUSHER_ADD = "MESSAGE_PUSHER_ADD";


export const SHOW_NEW_MESSAGE = "SHOW_NEW_MESSAGE";
export const CLEAR_NEW_MESSAGE = "CLEAR_NEW_MESSAGE";
