export const UPDATE_GALLERY_BEGIN = "UPDATE_GALLERY_BEGIN";
export const UPDATE_GALLERY_SUCCESS = "UPDATE_GALLERY_SUCCESS";
export const UPDATE_GALLERY_ERROR = "UPDATE_GALLERY_ERROR";

export const FETCH_MEDIA_BEGIN = "FETCH_MEDIA_BEGIN";
export const FETCH_MEDIA_SUCCESS = "FETCH_MEDIA_SUCCESS";
export const FETCH_MEDIA_ERROR = "FETCH_MEDIA_ERROR";

export const UPLOAD_MEDIA_BEGIN = "UPLOAD_MEDIA_BEGIN";
export const UPLOAD_MEDIA_SUCCESS = "UPLOAD_MEDIA_SUCCESS";
export const UPLOAD_MEDIA_ERROR = "UPLOAD_MEDIA_ERROR";

export const DELETE_MEDIA_BEGIN = "DELETE_MEDIA_BEGIN";
export const DELETE_MEDIA_SUCCESS = "DELETE_MEDIA_SUCCESS";
export const DELETE_MEDIA_ERROR = "DELETE_MEDIA_ERROR";

export const SET_GALLERYFORM_ERRORS = "SET_GALLERYFORM_ERRORS";
// export const CLEAR_GALLERYFORM_ERRORS = "CLEAR_GALLERYFORM_ERRORS";
