export const POST_PASSWORD_SUCCESS = "POST_PASSWORD_SUCCESS";
export const POST_PASSWORD_ERROR = "POST_PASSWORD_ERROR";

export const POST_USERNAME_BEGIN = "POST_USERNAME_BEGIN";
export const POST_USERNAME_SUCCESS = "POST_USERNAME_SUCCESS";
export const POST_USERNAME_ERROR = "POST_USERNAME_ERROR";

export const POST_DEACTIVATION_BEGIN = "POST_DEACTIVATION_BEGIN";
export const POST_DEACTIVATION_SUCCESS = "POST_DEACTIVATION_SUCCESS";
export const POST_DEACTIVATION_ERROR = "POST_DEACTIVATION_ERROR";

export const FETCH_USERNAME_BEGIN = "FETCH_USERNAME_BEGIN";
export const FETCH_USERNAME_SUCCESS = "FETCH_USERNAME_SUCCESS";
export const FETCH_USERNAME_ERROR = "FETCH_USERNAME_ERROR";
