export const FETCH_ORDERBYCODE_BEGIN = "FETCH_ORDERBYCODE_BEGIN";
export const FETCH_ORDERBYCODE_SUCCESS = "FETCH_ORDERBYCODE_SUCCESS";
export const FETCH_ORDERBYCODE_ERROR = "FETCH_ORDERBYCODE_ERROR";
export const FETCH_ORDERREQUIREMENT_ERROR = "FETCH_ORDERREQUIREMENT_ERROR";
export const FETCH_ORDERREQUIREMENT_SUCCESS = "FETCH_ORDERREQUIREMENT_SUCCESS";
export const FETCH_ORDERREQUIREMENT_BEGIN = "FETCH_ORDERREQUIREMENT_BEGIN";

export const HANDLE_LOADING_BEGIN = "HANDLE_LOADING_BEGIN";
export const HANDLE_LOADING_COMPLETE = "HANDLE_LOADING_COMPLETE";


